#include "web/server.h"

#include <httplib.h>

#include <algorithm>
#include <cctype>
#include <condition_variable>
#include <cstdio>
#include <deque>
#include <map>
#include <mutex>
#include <thread>

#include "core/crypto.h"
#include "core/env.h"
#include "core/secrets.h"
#include "web/guard.h"

namespace saga::web {

extern const std::string_view kIndexHtml;    // generated by cmake/embed.cmake
extern const std::string_view kLandingHtml;
extern const std::string_view kPrivacyHtml;
extern const std::string_view kMascotJs;
extern const std::string_view kBrandJs;
extern const std::string_view kLogoPng;

namespace {

using json = nlohmann::json;

std::string cookie(const httplib::Request& req, const std::string& name) {
  const std::string all = req.get_header_value("Cookie");
  const std::string key = name + "=";
  for (size_t p = 0; p < all.size();) {
    while (p < all.size() && (all[p] == ' ' || all[p] == ';')) ++p;
    const size_t e = all.find(';', p);
    const std::string kv = all.substr(p, e == std::string::npos ? std::string::npos : e - p);
    if (kv.starts_with(key)) return kv.substr(key.size());
    if (e == std::string::npos) break;
    p = e + 1;
  }
  return "";
}

// Namespaces embed the uid, so keep it to a safe, bounded alphabet.
std::string sanitize_uid(const std::string& s) {
  std::string out;
  for (char c : s) {
    const unsigned char u = static_cast<unsigned char>(c);
    if (std::isalnum(u) || c == '-' || c == '_') out += static_cast<char>(std::tolower(u));
    if (out.size() >= 80) break;  // room for a full 0x Sui address
  }
  return out;
}

// Wallet memory lives under the 0x address. A username that looks like one would open someone else's
// wallet memory without their signature, so usernames can't take that shape.
bool looks_like_address(const std::string& uid) {
  return uid.size() > 2 && uid.starts_with("0x") &&
         std::all_of(uid.begin() + 2, uid.end(), [](unsigned char c) { return std::isxdigit(c); });
}

void send_json(httplib::Response& res, const json& j, int status = 200) {
  res.status = status;
  res.set_content(j.dump(), "application/json");
}

// Broadcasts memory-write events to connected SSE clients.
struct Hub {
  std::mutex mu;
  std::condition_variable cv;
  std::deque<std::pair<uint64_t, memwal::WriteRecord>> events;
  uint64_t seq = 0;
  void push(const memwal::WriteRecord& r) {
    std::lock_guard lk(mu);
    events.emplace_back(++seq, r);
    while (events.size() > 500) events.pop_front();
    cv.notify_all();
  }
};

// The user's vault key: 32 bytes their browser derived from a wallet signature (base64url cookie).
// It lives in this request only; the server never stores it.
secrets::Key vault_of(const httplib::Request& req) {
  std::string v = cookie(req, "saga_vault");
  for (auto& c : v) c = c == '-' ? '+' : c == '_' ? '/' : c;
  try {
    auto k = crypto::b64_decode(v);
    return k.size() == 32 ? k : secrets::Key{};
  } catch (...) {
    return {};
  }
}

// A write is shown to the user it belongs to: their own namespaces, or shared-namespace writes their
// turns produced (blackboard, lessons, skills, improvements). Only content-free harness writes
// (prompt versions, scores) are public.
bool visible_to(const memwal::WriteRecord& r, const std::string& uid) {
  if (r.ns.starts_with("u:")) return r.ns.starts_with("u:" + uid + ":");
  return r.owner.empty() ? !r.ns.starts_with("task:") : r.owner == uid;
}

}  // namespace

int serve(harness::Harness& h, const ServerOptions& opt) {
  httplib::Server svr;
  svr.new_task_queue = [n = std::max(opt.threads, 8)] { return new httplib::ThreadPool(n); };
  svr.set_payload_max_length(kMaxHttpBody);
  auto hub = std::make_shared<Hub>();
  auto feeds = std::make_shared<Slots>(), chats = std::make_shared<Slots>();
  Auth auth(opt.auth);
  const std::string sec = opt.secure_cookies ? "; Secure" : "";
  RateLimiter limiter(std::max(opt.rate_per_ip, 1), std::max(opt.rate_global, 1));
  h.store().add_listener([hub](const memwal::WriteRecord& r) { hub->push(r); });

  auto client_ip = [&](const httplib::Request& req) {
    const bool loop = req.remote_addr == "127.0.0.1" || req.remote_addr == "::1";
    if (opt.trust_proxy && loop) {
      std::string xff = req.get_header_value("X-Forwarded-For");
      const auto comma = xff.find(',');
      if (comma != std::string::npos) xff.resize(comma);
      while (!xff.empty() && (xff.front() == ' ' || xff.front() == '\t')) xff.erase(xff.begin());
      while (!xff.empty() && (xff.back() == ' ' || xff.back() == '\t')) xff.pop_back();
      if (!xff.empty()) return xff;
    }
    return req.remote_addr;
  };

  // Headers are written after this runs, including on a 413 that never reached a handler.
  svr.set_post_routing_handler([](const httplib::Request&, httplib::Response& res) {
    res.set_header("X-Content-Type-Options", "nosniff");
    res.set_header("X-Frame-Options", "DENY");
    res.set_header("Referrer-Policy", "no-referrer");
    if (!res.has_header("Content-Security-Policy"))
      res.set_header("Content-Security-Policy", security_csp("", false));
  });
  svr.set_error_handler([](const httplib::Request&, httplib::Response& res) {
    if (res.body.empty() && !res.content_provider_ && res.status == 413)
      send_json(res, {{"error", "request body is too large"}}, 413);
    return httplib::Server::HandlerResponse::Handled;
  });

  // Host and rate checks happen before the body is read. Auth does too, so a missing session
  // is rejected without buffering. Mutation checks run after the body, in the pre-request handler.
  svr.set_pre_routing_handler([&](const httplib::Request& req, httplib::Response& res) {
    if (!host_allowed(req.get_header_value("Host"), opt.public_origin, opt.host)) {
      send_json(res, {{"error", "unexpected host"}}, 421);
      res.set_header("Connection", "close");
      return httplib::Server::HandlerResponse::Handled;
    }
    if (opt.rate_limit && !limiter.allow(client_ip(req))) {
      send_json(res, {{"error", "too many requests"}}, 429);
      res.set_header("Connection", "close");
      return httplib::Server::HandlerResponse::Handled;
    }
    if (!req.path.starts_with("/api/")) return httplib::Server::HandlerResponse::Unhandled;
    if (req.path == "/api/login" || req.path.starts_with("/api/auth/"))
      return httplib::Server::HandlerResponse::Unhandled;
    // Sign-in with Sui: every other API call needs a verified wallet session.
    if (auth.config().required && auth.session_address(cookie(req, "saga_session")).empty()) {
      send_json(res, {{"error", "sign in required"}, {"login", true}}, 401);
      return httplib::Server::HandlerResponse::Handled;
    }
    return httplib::Server::HandlerResponse::Unhandled;
  });
  svr.set_pre_request_handler([&](const httplib::Request& req, httplib::Response& res) {
    Mutation m;
    m.method = req.method;
    m.content_type = req.get_header_value("Content-Type");
    m.origin = req.get_header_value("Origin");
    m.fetch_site = req.get_header_value("Sec-Fetch-Site");
    m.body = req.body;
    m.csrf_cookie = cookie(req, "saga_csrf");
    m.csrf_header = req.get_header_value("X-CSRF-Token");
    m.expected_origin = opt.public_origin;
    if (m.expected_origin.empty()) {
      const std::string host = req.get_header_value("Host");
      if (!host.empty()) m.request_origin = (opt.secure_cookies ? "https://" : "http://") + host;
    }
    const Decision d = check_mutation(m);
    if (!d.ok()) {
      send_json(res, {{"error", d.error}}, d.status);
      return httplib::Server::HandlerResponse::Handled;
    }
    return httplib::Server::HandlerResponse::Unhandled;
  });
  // A field of the wrong JSON type ({"rating": "1"}) is the client's mistake, not a server error.
  svr.set_exception_handler([](const httplib::Request&, httplib::Response& res, std::exception_ptr ep) {
    try {
      std::rethrow_exception(ep);
    } catch (const nlohmann::json::exception&) {
      send_json(res, {{"error", "bad request: a field has the wrong type"}}, 400);
    } catch (const std::exception& e) {
      std::fprintf(stderr, "saga: request failed: %s\n", e.what());
      send_json(res, {{"error", "internal error"}}, 500);
    } catch (...) {
      send_json(res, {{"error", "internal error"}}, 500);
    }
  });
  auto uid_of = [&auth, &sec](const httplib::Request& req, httplib::Response& res) {
    // Signed in with a wallet (required, or chosen on the sign-in screen): the Sui address is the identity,
    // so memory follows the wallet anywhere.
    const std::string address = auth.session_address(cookie(req, "saga_session"));
    if (auth.config().required || !address.empty()) return address;
    std::string uid = sanitize_uid(cookie(req, "saga_uid"));
    if (uid.empty() || looks_like_address(uid)) {
      uid = "anon-" + crypto::uuid4().substr(0, 8);
      res.set_header("Set-Cookie", "saga_uid=" + uid + "; Path=/; Max-Age=31536000; SameSite=Lax" + sec);
    }
    return uid;
  };

  auto send_page = [&](const httplib::Request& req, httplib::Response& res, std::string_view page) {
    const std::string nonce = crypto::random_hex(16);
    std::string tok = cookie(req, "saga_csrf");
    if (tok.size() != 32 || !std::all_of(tok.begin(), tok.end(), [](unsigned char c) { return std::isxdigit(c); }))
      tok = crypto::random_hex(16);
    // Same value on every page of an open tab, so one tab's load doesn't invalidate another's token.
    res.headers.emplace("Set-Cookie", "saga_csrf=" + tok + "; Path=/; Max-Age=" + std::to_string(14 * 86400) +
                                          "; SameSite=Strict" + sec);
    std::string html(page);
    const std::string ph = "__SAGA_CSRF__";
    for (size_t at = 0; (at = html.find(ph, at)) != std::string::npos; at += tok.size())
      html.replace(at, ph.size(), tok);
    res.set_header("Content-Security-Policy", security_csp(nonce, true));
    res.set_header("Cache-Control", "no-cache");
    res.set_content(inject_nonce(std::move(html), nonce), "text/html; charset=utf-8");
  };
  svr.Get("/", [&](const httplib::Request& req, httplib::Response& res) { send_page(req, res, kLandingHtml); });
  svr.Get("/mascot.js", [](const httplib::Request&, httplib::Response& res) {
    res.set_header("Cache-Control", "no-cache");
    res.set_content(std::string(kMascotJs), "text/javascript; charset=utf-8");
  });
  svr.Get("/brand.js", [](const httplib::Request&, httplib::Response& res) {
    res.set_header("Cache-Control", "no-cache");
    res.set_content(std::string(kBrandJs), "text/javascript; charset=utf-8");
  });
  svr.Get("/saga-logo.png", [](const httplib::Request&, httplib::Response& res) {
    res.set_header("Cache-Control", "public, max-age=86400");
    res.set_content(std::string(kLogoPng), "image/png");
  });
  svr.Get("/privacy", [&](const httplib::Request& req, httplib::Response& res) { send_page(req, res, kPrivacyHtml); });
  svr.Get("/app", [&](const httplib::Request& req, httplib::Response& res) { send_page(req, res, kIndexHtml); });

  svr.Post("/api/login", [&](const httplib::Request& req, httplib::Response& res) {
    auto j = json::parse(req.body, nullptr, false);
    if (!j.is_object()) return send_json(res, {{"error", "bad json"}}, 400);
    if (auth.config().required) return send_json(res, {{"error", "This Saga only allows wallet sign-in."}}, 403);
    std::string handle = sanitize_uid(j.value("handle", ""));
    if (looks_like_address(handle))
      return send_json(res, {{"error", "That looks like a wallet address. Use Connect wallet to sign in with it."}}, 400);
    if (!handle.empty()) {
      res.headers.emplace("Set-Cookie", "saga_uid=" + handle + "; Path=/; Max-Age=31536000; SameSite=Lax" + sec);
      // Choosing a username leaves any wallet session, or the wallet would keep winning.
      res.headers.emplace("Set-Cookie", "saga_session=; Path=/; Max-Age=0; HttpOnly; SameSite=Lax" + sec);
    }
    send_json(res, {{"ok", true}, {"uid", handle}});
  });

  svr.Get("/api/me", [&](const httplib::Request& req, httplib::Response& res) {
    const std::string uid = uid_of(req, res);
    const std::string address = auth.session_address(cookie(req, "saga_session"));
    // auth: signed in with a wallet. wallet_required: this deployment only allows wallets.
    send_json(res, {{"uid", uid}, {"auth", !address.empty()},
                    {"address", address}, {"wallet_required", auth.config().required}});
  });

  // ---- Sign-in with Sui ----------------------------------------------------------------
  svr.Get("/api/auth/config", [&](const httplib::Request&, httplib::Response& res) {
    send_json(res, {{"required", auth.config().required}, {"network", "mainnet"}});
  });
  svr.Post("/api/auth/challenge", [&](const httplib::Request& req, httplib::Response& res) {
    auto j = json::parse(req.body, nullptr, false);
    const std::string address = normalize_address(j.is_object() ? j.value("address", "") : "");
    if (address.empty()) return send_json(res, {{"error", "a Sui address is required"}}, 400);
    // The name in the challenge is the configured origin. The request Host is not allowed to choose it.
    const std::string who = opt.public_origin.empty() ? req.get_header_value("Host") : origin_host(opt.public_origin);
    send_json(res, {{"message", auth.challenge(address, who)}});
  });
  svr.Post("/api/auth/verify", [&](const httplib::Request& req, httplib::Response& res) {
    auto j = json::parse(req.body, nullptr, false);
    if (!j.is_object()) return send_json(res, {{"error", "bad json"}}, 400);
    const std::string address = normalize_address(j.value("address", ""));
    std::string err;
    const std::string token = auth.verify(address, j.value("signature", ""), &err);
    if (token.empty()) return send_json(res, {{"error", err}}, 401);
    res.set_header("Set-Cookie", "saga_session=" + token + "; Path=/; Max-Age=" +
                                     std::to_string(auth.config().session_days * 86400) + "; HttpOnly; SameSite=Lax" + sec);
    send_json(res, {{"ok", true}, {"address", address}});
  });
  svr.Post("/api/auth/logout", [&](const httplib::Request&, httplib::Response& res) {
    res.set_header("Set-Cookie", "saga_session=; Path=/; Max-Age=0; HttpOnly; SameSite=Lax" + sec);
    res.headers.emplace("Set-Cookie", "saga_vault=; Path=/; Max-Age=0; SameSite=Strict" + sec);
    send_json(res, {{"ok", true}});
  });

  svr.Get("/api/state", [&](const httplib::Request& req, httplib::Response& res) {
    json s = h.state();
    const std::string uid = uid_of(req, res);
    json filtered = json::array();
    for (auto& w : h.store().recent(30))
      if (visible_to(w, uid)) filtered.push_back(w.to_json());
    s["recent_writes"] = filtered;
    s["uid"] = uid;
    s["agents"] = h.roster(uid);
    s["accounts"] = h.user_accounts() ? "user" : "host";
    send_json(res, s);
  });

  svr.Get("/api/memory/stats", [&](const httplib::Request& req, httplib::Response& res) {
    send_json(res, h.memory_stats(uid_of(req, res)));
  });
  svr.Get("/api/memory", [&](const httplib::Request& req, httplib::Response& res) {
    const std::string uid = uid_of(req, res);
    send_json(res, h.memory_view(uid, req.get_param_value("q")));
  });

  // Chat history and transcripts are read back from Walrus, not from a local store.
  svr.Get("/api/chats", [&](const httplib::Request& req, httplib::Response& res) {
    send_json(res, h.chat_history(uid_of(req, res)));
  });
  svr.Get(R"(/api/chats/([A-Za-z0-9_-]+))", [&](const httplib::Request& req, httplib::Response& res) {
    send_json(res, h.chat_transcript(uid_of(req, res), sanitize_uid(req.matches[1])));
  });
  svr.Get("/api/checkpoints", [&](const httplib::Request& req, httplib::Response& res) {
    send_json(res, h.checkpoints(uid_of(req, res), sanitize_uid(req.get_param_value("session"))));
  });
  svr.Post("/api/checkpoints/restore", [&](const httplib::Request& req, httplib::Response& res) {
    auto j = json::parse(req.body, nullptr, false);
    const std::string session = j.is_object() ? sanitize_uid(j.value("session", "")) : "";
    if (session.empty()) return send_json(res, {{"error", "session required"}}, 400);
    send_json(res, h.restore_checkpoints(uid_of(req, res), session));
  });

  // Agents: provider sign-in + usage windows, and users' own API-key agents.
  svr.Get("/api/agents", [&](const httplib::Request& req, httplib::Response& res) {
    send_json(res, h.agents_view(uid_of(req, res), vault_of(req)));
  });
  svr.Post("/api/agents/connect", [&](const httplib::Request& req, httplib::Response& res) {
    auto j = json::parse(req.body, nullptr, false);
    const std::string agent = j.is_object() ? j.value("agent", "") : "";
    // Operator mode signs in the *host's* CLIs, so it is only offered when Saga serves this machine alone.
    if (!h.user_accounts() && opt.host != "127.0.0.1" && opt.host != "localhost")
      return send_json(res, {{"error", "connect provider accounts on the Saga host"}}, 403);
    auto r = h.connect_agent(uid_of(req, res), agent, vault_of(req));
    send_json(res, r, r.contains("error") ? 400 : 200);
  });
  svr.Get("/api/agents/connect", [&](const httplib::Request& req, httplib::Response& res) {
    send_json(res, h.connect_status(uid_of(req, res), req.get_param_value("agent"), vault_of(req)));
  });
  svr.Post("/api/agents/credential", [&](const httplib::Request& req, httplib::Response& res) {
    auto j = json::parse(req.body, nullptr, false);
    if (!j.is_object()) return send_json(res, {{"error", "bad json"}}, 400);
    auto r = h.set_credential(uid_of(req, res), j.value("agent", ""), j.value("kind", ""), j.value("value", ""),
                              vault_of(req));
    send_json(res, r, r.contains("error") ? 400 : 200);
  });
  svr.Post("/api/agents/disconnect", [&](const httplib::Request& req, httplib::Response& res) {
    auto j = json::parse(req.body, nullptr, false);
    // Like Connect: in operator mode this signs out the host's own CLIs, so only on this machine.
    if (!h.user_accounts() && opt.host != "127.0.0.1" && opt.host != "localhost")
      return send_json(res, {{"error", "disconnect provider accounts on the Saga host"}}, 403);
    auto r = h.disconnect_agent(uid_of(req, res), j.is_object() ? j.value("agent", "") : "", vault_of(req));
    send_json(res, r, r.contains("error") ? 400 : 200);
  });
  svr.Post("/api/agents/probe", [&](const httplib::Request& req, httplib::Response& res) {
    auto j = json::parse(req.body, nullptr, false);
    send_json(res, h.probe_agent(uid_of(req, res), j.is_object() ? j.value("agent", "") : "", vault_of(req)));
  });
  svr.Post("/api/agents", [&](const httplib::Request& req, httplib::Response& res) {
    auto j = json::parse(req.body, nullptr, false);
    if (!j.is_object()) return send_json(res, {{"error", "bad json"}}, 400);
    auto r = h.add_agent(uid_of(req, res), j, vault_of(req));
    send_json(res, r, r.contains("error") ? 400 : 200);
  });
  svr.Get("/api/models", [&](const httplib::Request& req, httplib::Response& res) {
    send_json(res, h.models_view(uid_of(req, res)));
  });
  svr.Post("/api/agents/model", [&](const httplib::Request& req, httplib::Response& res) {
    auto j = json::parse(req.body, nullptr, false);
    if (!j.is_object()) j = json::object();
    const json r = h.set_model(uid_of(req, res), j.value("agent", ""), j.value("model", ""));
    send_json(res, r, r.contains("error") ? 400 : 200);
  });
  svr.Post("/api/agents/remove", [&](const httplib::Request& req, httplib::Response& res) {
    auto j = json::parse(req.body, nullptr, false);
    send_json(res, h.remove_agent(uid_of(req, res), j.is_object() ? j.value("name", "") : "", vault_of(req)));
  });

  // ---- GitHub ------------------------------------------------------------------------------
  auto body_of = [](const httplib::Request& req) {
    auto j = json::parse(req.body, nullptr, false);
    return j.is_object() ? j : json::object();
  };
  auto reply = [](httplib::Response& res, const json& r) { send_json(res, r, r.contains("error") ? 400 : 200); };
  svr.Get("/api/github", [&](const httplib::Request& req, httplib::Response& res) {
    send_json(res, h.github_status(uid_of(req, res), vault_of(req)));
  });
  svr.Post("/api/github/token", [&](const httplib::Request& req, httplib::Response& res) {
    reply(res, h.github_set_token(uid_of(req, res), body_of(req).value("token", ""), vault_of(req)));
  });
  svr.Post("/api/github/device", [&](const httplib::Request& req, httplib::Response& res) {
    reply(res, h.github_device(uid_of(req, res), vault_of(req)));
  });
  // "Connect GitHub": off to github.com to authorize, back via the callback, then the app finishes the
  // exchange in a same-site request, the only kind that carries the (SameSite=Strict) vault cookie.
  auto site_of = [&](const httplib::Request& req) {
    // Wallet challenges and the GitHub redirect use the configured origin, never a forwarded header.
    if (!opt.public_origin.empty()) return opt.public_origin;
    return std::string("http://") + req.get_header_value("Host");
  };
  svr.Get("/api/github/login", [&](const httplib::Request& req, httplib::Response& res) {
    const std::string state = crypto::uuid4();
    const std::string url = h.github_authorize_url(site_of(req) + "/api/github/callback", state);
    if (url.empty()) return res.set_redirect("/app?gh_error=not_configured");
    res.set_header("Set-Cookie", "saga_gh_state=" + state + "; Path=/; Max-Age=600; HttpOnly; SameSite=Lax" + sec);
    res.set_redirect(url);
  });
  svr.Get("/api/github/callback", [&](const httplib::Request& req, httplib::Response& res) {
    // Only [A-Za-z0-9-] ever comes back from GitHub here; anything else is dropped rather than echoed.
    auto clean = [](std::string s) { std::erase_if(s, [](char c) { return !std::isalnum(static_cast<unsigned char>(c)) && c != '-' && c != '_'; }); return s.substr(0, 200); };
    if (req.has_param("error")) return res.set_redirect("/app?gh_error=" + clean(req.get_param_value("error")));
    res.set_redirect("/app?gh_code=" + clean(req.get_param_value("code")) + "&gh_state=" + clean(req.get_param_value("state")));
  });
  svr.Post("/api/github/finish", [&](const httplib::Request& req, httplib::Response& res) {
    const json j = body_of(req);
    const std::string state = cookie(req, "saga_gh_state");
    if (state.empty() || j.value("state", "") != state) return send_json(res, {{"error", "that GitHub sign-in expired — try Connect again"}}, 400);
    const std::string uid = uid_of(req, res);
    res.set_header("Set-Cookie", "saga_gh_state=; Path=/; Max-Age=0; HttpOnly; SameSite=Lax" + sec);
    reply(res, h.github_oauth_finish(uid, j.value("code", ""), site_of(req) + "/api/github/callback", vault_of(req)));
  });
  svr.Post("/api/github/disconnect", [&](const httplib::Request& req, httplib::Response& res) {
    send_json(res, h.github_disconnect(uid_of(req, res), vault_of(req)));
  });
  svr.Get("/api/github/repos", [&](const httplib::Request& req, httplib::Response& res) {
    reply(res, h.github_repos(uid_of(req, res), vault_of(req)));
  });
  svr.Post("/api/github/attach", [&](const httplib::Request& req, httplib::Response& res) {
    const json j = body_of(req);
    const std::string session = sanitize_uid(j.value("session", ""));
    if (session.empty()) return send_json(res, {{"error", "session required"}}, 400);
    reply(res, h.github_attach(uid_of(req, res), session, j.value("repo", ""), vault_of(req)));
  });
  svr.Get("/api/github/repo", [&](const httplib::Request& req, httplib::Response& res) {
    const std::string session = sanitize_uid(req.get_param_value("session"));
    if (session.empty()) return send_json(res, {{"repo", nullptr}});
    send_json(res, h.github_repo(uid_of(req, res), session, vault_of(req)));
  });
  svr.Post("/api/github/pr", [&](const httplib::Request& req, httplib::Response& res) {
    const json j = body_of(req);
    const std::string session = sanitize_uid(j.value("session", ""));
    if (session.empty()) return send_json(res, {{"error", "session required"}}, 400);
    reply(res, h.github_open_pr(uid_of(req, res), session, j.value("title", ""), vault_of(req)));
  });

  // Vault: is the key this browser holds the one this user's secrets are sealed with?
  svr.Get("/api/vault", [&](const httplib::Request& req, httplib::Response& res) {
    send_json(res, h.vault_status(uid_of(req, res), vault_of(req)));
  });
  svr.Post("/api/vault/reset", [&](const httplib::Request& req, httplib::Response& res) {
    send_json(res, h.vault_reset(uid_of(req, res), vault_of(req)));
  });

  svr.Post("/api/chat", [&](const httplib::Request& req, httplib::Response& res) {
    auto j = json::parse(req.body, nullptr, false);
    const std::string msg = j.is_object() ? j.value("message", "") : "";
    if (msg.empty() || msg.size() > kMaxChatMessage)
      return send_json(res, {{"error", "message required (≤20k chars)"}}, 400);
    const std::string uid = uid_of(req, res);
    std::string session = sanitize_uid(j.value("session", ""));
    if (session.empty()) session = uid;
    if (const int slot = chats->take(uid, opt.chats_per_user, opt.chats_global))
      return send_json(res, {{"error", slot == 1
                                           ? "you already have " + std::to_string(opt.chats_per_user) +
                                                 " chats running — wait for one to finish"
                                           : "too many chats are running on this Saga — try again shortly"}},
                       429);

    struct Stream {
      std::mutex mu;
      std::condition_variable cv;
      std::deque<std::string> lines;
      bool done = false;
      std::string turn_id;
    };
    auto st = std::make_shared<Stream>();
    const secrets::Key vault = vault_of(req);
    std::thread([&h, st, uid, session, msg, vault, chats] {
      auto emit = [st](const json& e) {
        std::lock_guard lk(st->mu);
        if (e.value("type", "") == "turn") st->turn_id = e.value("turn_id", "");
        st->lines.push_back(e.dump() + "\n");
        st->cv.notify_all();
      };
      try {
        h.chat(uid, session, msg, emit, vault);
      } catch (const std::exception& ex) {
        emit({{"type", "error"}, {"text", ex.what()}});
      }
      chats->give(uid);  // the turn itself is over, even if the browser left earlier
      std::lock_guard lk(st->mu);
      st->done = true;
      st->cv.notify_all();
    }).detach();

    res.set_header("Cache-Control", "no-cache");
    res.set_header("X-Accel-Buffering", "no");
    res.set_chunked_content_provider("application/x-ndjson", [&h, st, uid](size_t, httplib::DataSink& sink) {
      std::unique_lock lk(st->mu);
      st->cv.wait_for(lk, std::chrono::seconds(15), [&] { return st->done || !st->lines.empty(); });
      if (st->lines.empty() && !st->done) {
        lk.unlock();
        const std::string ping = "{\"type\":\"ping\"}\n";
        if (!sink.write(ping.data(), ping.size()) && !st->turn_id.empty()) h.cancel(uid, st->turn_id);
        return true;
      }
      while (!st->lines.empty()) {
        std::string line = std::move(st->lines.front());
        st->lines.pop_front();
        lk.unlock();
        if (!sink.write(line.data(), line.size())) {  // browser went away → stop the agents
          if (!st->turn_id.empty()) h.cancel(uid, st->turn_id);
          return false;
        }
        lk.lock();
      }
      if (st->done) sink.done();
      return true;
    });
  });

  svr.Post("/api/feedback", [&](const httplib::Request& req, httplib::Response& res) {
    auto j = json::parse(req.body, nullptr, false);
    if (!j.is_object()) return send_json(res, {{"error", "bad json"}}, 400);
    const int rating = j.value("rating", 0);
    if (rating != 1 && rating != -1) return send_json(res, {{"error", "rating must be 1 or -1"}}, 400);
    const std::string comment = j.value("comment", "");
    if (comment.size() > kMaxFeedback) return send_json(res, {{"error", "comment must be at most 4096 bytes"}}, 400);
    send_json(res, h.feedback(uid_of(req, res), j.value("turn_id", ""), rating, comment));
  });

  svr.Post("/api/cancel", [&](const httplib::Request& req, httplib::Response& res) {
    auto j = json::parse(req.body, nullptr, false);
    send_json(res, {{"ok", j.is_object() && h.cancel(uid_of(req, res), j.value("turn_id", ""))}});
  });

  // Live feed of Walrus writes (Server-Sent Events).
  svr.Get("/api/writes", [&](const httplib::Request& req, httplib::Response& res) {
    const std::string uid = uid_of(req, res);
    if (const int slot = feeds->take(uid, opt.feeds_per_user, opt.feeds_global))
      return send_json(res, {{"error", slot == 1 ? "too many open Saga tabs"
                                                 : "too many live tabs are open on this Saga — try again shortly"}},
                       429);
    auto cursor = std::make_shared<uint64_t>(0);
    {
      std::lock_guard lk(hub->mu);
      *cursor = hub->seq;
    }
    res.set_header("Cache-Control", "no-cache");
    res.set_chunked_content_provider("text/event-stream", [hub, cursor, uid](size_t, httplib::DataSink& sink) {
      std::vector<memwal::WriteRecord> out;
      {
        std::unique_lock lk(hub->mu);
        hub->cv.wait_for(lk, std::chrono::seconds(15), [&] { return hub->seq > *cursor; });
        for (auto& [s, r] : hub->events)
          if (s > *cursor && visible_to(r, uid)) out.push_back(r);
        *cursor = hub->seq;
      }
      std::string payload = out.empty() ? ": keepalive\n\n" : "";
      for (auto& r : out) payload += "data: " + r.to_json().dump() + "\n\n";
      return sink.write(payload.data(), payload.size());
    }, [feeds, uid](bool) { feeds->give(uid); });
  });

  std::printf("saga: listening on http://%s:%d\n", opt.host.c_str(), opt.port);
  std::fflush(stdout);
  if (!svr.listen(opt.host, opt.port)) {
    std::fprintf(stderr, "saga: cannot listen on %s:%d\n", opt.host.c_str(), opt.port);
    return 1;
  }
  return 0;
}

}  // namespace saga::web
