#include "web/server.h"

#include <httplib.h>

#include <algorithm>
#include <cctype>
#include <condition_variable>
#include <cstdio>
#include <deque>
#include <mutex>
#include <thread>

#include "core/crypto.h"
#include "core/env.h"
#include "core/secrets.h"

namespace saga::web {

extern const std::string_view kIndexHtml;    // generated by cmake/embed.cmake
extern const std::string_view kLandingHtml;
extern const std::string_view kPrivacyHtml;

namespace {

using json = nlohmann::json;

std::string cookie(const httplib::Request& req, const std::string& name) {
  const std::string all = req.get_header_value("Cookie");
  const std::string key = name + "=";
  for (size_t p = 0; p < all.size();) {
    while (p < all.size() && (all[p] == ' ' || all[p] == ';')) ++p;
    const size_t e = all.find(';', p);
    const std::string kv = all.substr(p, e == std::string::npos ? std::string::npos : e - p);
    if (kv.starts_with(key)) return kv.substr(key.size());
    if (e == std::string::npos) break;
    p = e + 1;
  }
  return "";
}

// Namespaces embed the uid, so keep it to a safe, bounded alphabet.
std::string sanitize_uid(const std::string& s) {
  std::string out;
  for (char c : s) {
    const unsigned char u = static_cast<unsigned char>(c);
    if (std::isalnum(u) || c == '-' || c == '_') out += static_cast<char>(std::tolower(u));
    if (out.size() >= 80) break;  // room for a full 0x Sui address
  }
  return out;
}

void send_json(httplib::Response& res, const json& j, int status = 200) {
  res.status = status;
  res.set_content(j.dump(), "application/json");
}

// Broadcasts memory-write events to connected SSE clients.
struct Hub {
  std::mutex mu;
  std::condition_variable cv;
  std::deque<std::pair<uint64_t, memwal::WriteRecord>> events;
  uint64_t seq = 0;
  void push(const memwal::WriteRecord& r) {
    std::lock_guard lk(mu);
    events.emplace_back(++seq, r);
    while (events.size() > 500) events.pop_front();
    cv.notify_all();
  }
};

// The user's vault key: 32 bytes their browser derived from a wallet signature (base64url cookie).
// It lives in this request only; the server never stores it.
secrets::Key vault_of(const httplib::Request& req) {
  std::string v = cookie(req, "saga_vault");
  for (auto& c : v) c = c == '-' ? '+' : c == '_' ? '/' : c;
  try {
    auto k = crypto::b64_decode(v);
    return k.size() == 32 ? k : secrets::Key{};
  } catch (...) {
    return {};
  }
}

bool visible_to(const std::string& ns, const std::string& uid) {
  return ns.starts_with("u:" + uid + ":") || !ns.starts_with("u:");
}

}  // namespace

int serve(harness::Harness& h, const ServerOptions& opt) {
  httplib::Server svr;
  svr.new_task_queue = [] { return new httplib::ThreadPool(48); };
  auto hub = std::make_shared<Hub>();
  Auth auth(opt.auth);
  h.store().add_listener([hub](const memwal::WriteRecord& r) { hub->push(r); });

  // Identity + optional access gate.
  svr.set_pre_routing_handler([&](const httplib::Request& req, httplib::Response& res) {
    if (!req.path.starts_with("/api/")) return httplib::Server::HandlerResponse::Unhandled;
    if (req.path == "/api/login" || req.path.starts_with("/api/auth/")) return httplib::Server::HandlerResponse::Unhandled;
    if (!opt.access_code.empty() && cookie(req, "saga_access") != opt.access_code) {
      send_json(res, {{"error", "access code required"}}, 401);
      return httplib::Server::HandlerResponse::Handled;
    }
    // Sign-in with Sui: every other API call needs a verified wallet session.
    if (auth.config().required && auth.session_address(cookie(req, "saga_session")).empty()) {
      send_json(res, {{"error", "sign in required"}, {"login", true}}, 401);
      return httplib::Server::HandlerResponse::Handled;
    }
    return httplib::Server::HandlerResponse::Unhandled;
  });
  auto uid_of = [&auth](const httplib::Request& req, httplib::Response& res) {
    // Signed in: the Sui address is the identity, so memory follows the wallet anywhere.
    if (auth.config().required) return auth.session_address(cookie(req, "saga_session"));
    std::string uid = sanitize_uid(cookie(req, "saga_uid"));
    if (uid.empty()) {
      uid = "anon-" + crypto::uuid4().substr(0, 8);
      res.set_header("Set-Cookie", "saga_uid=" + uid + "; Path=/; Max-Age=31536000; SameSite=Lax");
    }
    return uid;
  };

  svr.Get("/", [](const httplib::Request&, httplib::Response& res) {
    res.set_header("Cache-Control", "no-cache");  // always serve the page this binary embeds
    res.set_content(std::string(kLandingHtml), "text/html; charset=utf-8");
  });
  svr.Get("/privacy", [](const httplib::Request&, httplib::Response& res) {
    res.set_header("Cache-Control", "no-cache");
    res.set_content(std::string(kPrivacyHtml), "text/html; charset=utf-8");
  });
  svr.Get("/app", [](const httplib::Request&, httplib::Response& res) {
    res.set_header("Cache-Control", "no-cache");  // always serve the page this binary embeds
    res.set_content(std::string(kIndexHtml), "text/html; charset=utf-8");
  });

  svr.Post("/api/login", [&](const httplib::Request& req, httplib::Response& res) {
    auto j = json::parse(req.body, nullptr, false);
    if (!j.is_object()) return send_json(res, {{"error", "bad json"}}, 400);
    const std::string code = j.value("access_code", "");
    const bool already_in = !opt.access_code.empty() && cookie(req, "saga_access") == opt.access_code;
    if (!opt.access_code.empty() && code != opt.access_code && !already_in)
      return send_json(res, {{"error", "wrong code"}}, 401);
    std::string handle = sanitize_uid(j.value("handle", ""));
    if (!opt.access_code.empty() && !already_in)
      res.set_header("Set-Cookie", "saga_access=" + code + "; Path=/; Max-Age=31536000; HttpOnly; SameSite=Lax");
    if (!handle.empty())
      res.headers.emplace("Set-Cookie", "saga_uid=" + handle + "; Path=/; Max-Age=31536000; SameSite=Lax");
    send_json(res, {{"ok", true}, {"uid", handle}});
  });

  svr.Get("/api/me", [&](const httplib::Request& req, httplib::Response& res) {
    const std::string uid = uid_of(req, res);
    send_json(res, {{"uid", uid}, {"gated", !opt.access_code.empty()}, {"auth", auth.config().required},
                    {"address", auth.config().required ? uid : ""}});
  });

  // ---- Sign-in with Sui ----------------------------------------------------------------
  svr.Get("/api/auth/config", [&](const httplib::Request&, httplib::Response& res) {
    send_json(res, {{"required", auth.config().required}, {"network", "mainnet"}});
  });
  svr.Post("/api/auth/challenge", [&](const httplib::Request& req, httplib::Response& res) {
    auto j = json::parse(req.body, nullptr, false);
    const std::string address = normalize_address(j.is_object() ? j.value("address", "") : "");
    if (address.empty()) return send_json(res, {{"error", "a Sui address is required"}}, 400);
    send_json(res, {{"message", auth.challenge(address, req.get_header_value("Host"))}});
  });
  svr.Post("/api/auth/verify", [&](const httplib::Request& req, httplib::Response& res) {
    auto j = json::parse(req.body, nullptr, false);
    if (!j.is_object()) return send_json(res, {{"error", "bad json"}}, 400);
    const std::string address = normalize_address(j.value("address", ""));
    std::string err;
    const std::string token = auth.verify(address, j.value("signature", ""), &err);
    if (token.empty()) return send_json(res, {{"error", err}}, 401);
    res.set_header("Set-Cookie", "saga_session=" + token + "; Path=/; Max-Age=" +
                                     std::to_string(auth.config().session_days * 86400) + "; HttpOnly; SameSite=Lax");
    send_json(res, {{"ok", true}, {"address", address}});
  });
  svr.Post("/api/auth/logout", [&](const httplib::Request&, httplib::Response& res) {
    res.set_header("Set-Cookie", "saga_session=; Path=/; Max-Age=0; HttpOnly; SameSite=Lax");
    res.headers.emplace("Set-Cookie", "saga_vault=; Path=/; Max-Age=0; SameSite=Strict");
    send_json(res, {{"ok", true}});
  });

  svr.Get("/api/state", [&](const httplib::Request& req, httplib::Response& res) {
    json s = h.state();
    const std::string uid = uid_of(req, res);
    json filtered = json::array();
    for (auto& w : s["recent_writes"])
      if (visible_to(w.value("namespace", ""), uid)) filtered.push_back(w);
    s["recent_writes"] = filtered;
    s["uid"] = uid;
    s["agents"] = h.roster(uid);
    s["accounts"] = h.user_accounts() ? "user" : "host";
    send_json(res, s);
  });

  svr.Get("/api/memory/stats", [&](const httplib::Request& req, httplib::Response& res) {
    send_json(res, h.memory_stats(uid_of(req, res)));
  });
  svr.Get("/api/memory", [&](const httplib::Request& req, httplib::Response& res) {
    const std::string uid = uid_of(req, res);
    send_json(res, h.memory_view(uid, req.get_param_value("q")));
  });

  // Chat history and transcripts are read back from Walrus, not from a local store.
  svr.Get("/api/chats", [&](const httplib::Request& req, httplib::Response& res) {
    send_json(res, h.chat_history(uid_of(req, res)));
  });
  svr.Get(R"(/api/chats/([A-Za-z0-9_-]+))", [&](const httplib::Request& req, httplib::Response& res) {
    send_json(res, h.chat_transcript(uid_of(req, res), sanitize_uid(req.matches[1])));
  });
  svr.Get("/api/checkpoints", [&](const httplib::Request& req, httplib::Response& res) {
    send_json(res, h.checkpoints(uid_of(req, res), sanitize_uid(req.get_param_value("session"))));
  });
  svr.Post("/api/checkpoints/restore", [&](const httplib::Request& req, httplib::Response& res) {
    auto j = json::parse(req.body, nullptr, false);
    const std::string session = j.is_object() ? sanitize_uid(j.value("session", "")) : "";
    if (session.empty()) return send_json(res, {{"error", "session required"}}, 400);
    send_json(res, h.restore_checkpoints(uid_of(req, res), session));
  });

  // Agents: provider sign-in + usage windows, and users' own API-key agents.
  svr.Get("/api/agents", [&](const httplib::Request& req, httplib::Response& res) {
    send_json(res, h.agents_view(uid_of(req, res), vault_of(req)));
  });
  svr.Post("/api/agents/connect", [&](const httplib::Request& req, httplib::Response& res) {
    auto j = json::parse(req.body, nullptr, false);
    const std::string agent = j.is_object() ? j.value("agent", "") : "";
    // Operator mode signs in the *host's* CLIs, so it is only offered on a private deployment.
    if (!h.user_accounts() && !opt.access_code.empty())
      return send_json(res, {{"error", "connect provider accounts on the Saga host"}}, 403);
    auto r = h.connect_agent(uid_of(req, res), agent, vault_of(req));
    send_json(res, r, r.contains("error") ? 400 : 200);
  });
  svr.Get("/api/agents/connect", [&](const httplib::Request& req, httplib::Response& res) {
    send_json(res, h.connect_status(uid_of(req, res), req.get_param_value("agent")));
  });
  svr.Post("/api/agents/credential", [&](const httplib::Request& req, httplib::Response& res) {
    auto j = json::parse(req.body, nullptr, false);
    if (!j.is_object()) return send_json(res, {{"error", "bad json"}}, 400);
    auto r = h.set_credential(uid_of(req, res), j.value("agent", ""), j.value("kind", ""), j.value("value", ""),
                              vault_of(req));
    send_json(res, r, r.contains("error") ? 400 : 200);
  });
  svr.Post("/api/agents/disconnect", [&](const httplib::Request& req, httplib::Response& res) {
    auto j = json::parse(req.body, nullptr, false);
    send_json(res, h.disconnect_agent(uid_of(req, res), j.is_object() ? j.value("agent", "") : ""));
  });
  svr.Post("/api/agents/probe", [&](const httplib::Request& req, httplib::Response& res) {
    auto j = json::parse(req.body, nullptr, false);
    send_json(res, h.probe_agent(uid_of(req, res), j.is_object() ? j.value("agent", "") : "", vault_of(req)));
  });
  svr.Post("/api/agents", [&](const httplib::Request& req, httplib::Response& res) {
    auto j = json::parse(req.body, nullptr, false);
    if (!j.is_object()) return send_json(res, {{"error", "bad json"}}, 400);
    auto r = h.add_agent(uid_of(req, res), j, vault_of(req));
    send_json(res, r, r.contains("error") ? 400 : 200);
  });
  svr.Get("/api/models", [&](const httplib::Request& req, httplib::Response& res) {
    send_json(res, h.models_view(uid_of(req, res)));
  });
  svr.Post("/api/agents/model", [&](const httplib::Request& req, httplib::Response& res) {
    auto j = json::parse(req.body, nullptr, false);
    if (!j.is_object()) j = json::object();
    const json r = h.set_model(uid_of(req, res), j.value("agent", ""), j.value("model", ""));
    send_json(res, r, r.contains("error") ? 400 : 200);
  });
  svr.Post("/api/agents/remove", [&](const httplib::Request& req, httplib::Response& res) {
    auto j = json::parse(req.body, nullptr, false);
    send_json(res, h.remove_agent(uid_of(req, res), j.is_object() ? j.value("name", "") : ""));
  });

  // ---- GitHub ------------------------------------------------------------------------------
  auto body_of = [](const httplib::Request& req) {
    auto j = json::parse(req.body, nullptr, false);
    return j.is_object() ? j : json::object();
  };
  auto reply = [](httplib::Response& res, const json& r) { send_json(res, r, r.contains("error") ? 400 : 200); };
  svr.Get("/api/github", [&](const httplib::Request& req, httplib::Response& res) {
    send_json(res, h.github_status(uid_of(req, res), vault_of(req)));
  });
  svr.Post("/api/github/token", [&](const httplib::Request& req, httplib::Response& res) {
    reply(res, h.github_set_token(uid_of(req, res), body_of(req).value("token", ""), vault_of(req)));
  });
  svr.Post("/api/github/device", [&](const httplib::Request& req, httplib::Response& res) {
    reply(res, h.github_device(uid_of(req, res), vault_of(req)));
  });
  // "Connect GitHub": off to github.com to authorize, back via the callback, then the app finishes the
  // exchange in a same-site request, the only kind that carries the (SameSite=Strict) vault cookie.
  auto site_of = [](const httplib::Request& req) {
    if (auto u = env::get("SAGA_PUBLIC_URL"); !u.empty()) return u;
    const std::string proto = req.get_header_value("X-Forwarded-Proto");
    return (proto.empty() ? "http" : proto) + "://" + req.get_header_value("Host");
  };
  svr.Get("/api/github/login", [&](const httplib::Request& req, httplib::Response& res) {
    const std::string state = crypto::uuid4();
    const std::string url = h.github_authorize_url(site_of(req) + "/api/github/callback", state);
    if (url.empty()) return res.set_redirect("/app?gh_error=not_configured");
    res.set_header("Set-Cookie", "saga_gh_state=" + state + "; Path=/; Max-Age=600; HttpOnly; SameSite=Lax");
    res.set_redirect(url);
  });
  svr.Get("/api/github/callback", [&](const httplib::Request& req, httplib::Response& res) {
    // Only [A-Za-z0-9-] ever comes back from GitHub here; anything else is dropped rather than echoed.
    auto clean = [](std::string s) { std::erase_if(s, [](char c) { return !std::isalnum(static_cast<unsigned char>(c)) && c != '-' && c != '_'; }); return s.substr(0, 200); };
    if (req.has_param("error")) return res.set_redirect("/app?gh_error=" + clean(req.get_param_value("error")));
    res.set_redirect("/app?gh_code=" + clean(req.get_param_value("code")) + "&gh_state=" + clean(req.get_param_value("state")));
  });
  svr.Post("/api/github/finish", [&](const httplib::Request& req, httplib::Response& res) {
    const json j = body_of(req);
    const std::string state = cookie(req, "saga_gh_state");
    if (state.empty() || j.value("state", "") != state) return send_json(res, {{"error", "that GitHub sign-in expired — try Connect again"}}, 400);
    const std::string uid = uid_of(req, res);
    res.set_header("Set-Cookie", "saga_gh_state=; Path=/; Max-Age=0; HttpOnly; SameSite=Lax");
    reply(res, h.github_oauth_finish(uid, j.value("code", ""), site_of(req) + "/api/github/callback", vault_of(req)));
  });
  svr.Post("/api/github/disconnect", [&](const httplib::Request& req, httplib::Response& res) {
    send_json(res, h.github_disconnect(uid_of(req, res)));
  });
  svr.Get("/api/github/repos", [&](const httplib::Request& req, httplib::Response& res) {
    reply(res, h.github_repos(uid_of(req, res), vault_of(req)));
  });
  svr.Post("/api/github/attach", [&](const httplib::Request& req, httplib::Response& res) {
    const json j = body_of(req);
    const std::string session = sanitize_uid(j.value("session", ""));
    if (session.empty()) return send_json(res, {{"error", "session required"}}, 400);
    reply(res, h.github_attach(uid_of(req, res), session, j.value("repo", ""), vault_of(req)));
  });
  svr.Get("/api/github/repo", [&](const httplib::Request& req, httplib::Response& res) {
    const std::string session = sanitize_uid(req.get_param_value("session"));
    if (session.empty()) return send_json(res, {{"repo", nullptr}});
    send_json(res, h.github_repo(uid_of(req, res), session, vault_of(req)));
  });
  svr.Post("/api/github/pr", [&](const httplib::Request& req, httplib::Response& res) {
    const json j = body_of(req);
    const std::string session = sanitize_uid(j.value("session", ""));
    if (session.empty()) return send_json(res, {{"error", "session required"}}, 400);
    reply(res, h.github_open_pr(uid_of(req, res), session, j.value("title", ""), vault_of(req)));
  });

  // Vault: is the key this browser holds the one this user's secrets are sealed with?
  svr.Get("/api/vault", [&](const httplib::Request& req, httplib::Response& res) {
    send_json(res, h.vault_status(uid_of(req, res), vault_of(req)));
  });
  svr.Post("/api/vault/reset", [&](const httplib::Request& req, httplib::Response& res) {
    send_json(res, h.vault_reset(uid_of(req, res), vault_of(req)));
  });

  svr.Post("/api/chat", [&](const httplib::Request& req, httplib::Response& res) {
    auto j = json::parse(req.body, nullptr, false);
    const std::string msg = j.is_object() ? j.value("message", "") : "";
    if (msg.empty() || msg.size() > 20000) return send_json(res, {{"error", "message required (≤20k chars)"}}, 400);
    const std::string uid = uid_of(req, res);
    std::string session = sanitize_uid(j.value("session", ""));
    if (session.empty()) session = uid;

    struct Stream {
      std::mutex mu;
      std::condition_variable cv;
      std::deque<std::string> lines;
      bool done = false;
      std::string turn_id;
    };
    auto st = std::make_shared<Stream>();
    const secrets::Key vault = vault_of(req);
    std::thread([&h, st, uid, session, msg, vault] {
      auto emit = [st](const json& e) {
        std::lock_guard lk(st->mu);
        if (e.value("type", "") == "turn") st->turn_id = e.value("turn_id", "");
        st->lines.push_back(e.dump() + "\n");
        st->cv.notify_all();
      };
      try {
        h.chat(uid, session, msg, emit, vault);
      } catch (const std::exception& ex) {
        emit({{"type", "error"}, {"text", ex.what()}});
      }
      std::lock_guard lk(st->mu);
      st->done = true;
      st->cv.notify_all();
    }).detach();

    res.set_header("Cache-Control", "no-cache");
    res.set_header("X-Accel-Buffering", "no");
    res.set_chunked_content_provider("application/x-ndjson", [&h, st](size_t, httplib::DataSink& sink) {
      std::unique_lock lk(st->mu);
      st->cv.wait_for(lk, std::chrono::seconds(15), [&] { return st->done || !st->lines.empty(); });
      if (st->lines.empty() && !st->done) {
        lk.unlock();
        const std::string ping = "{\"type\":\"ping\"}\n";
        if (!sink.write(ping.data(), ping.size()) && !st->turn_id.empty()) h.cancel(st->turn_id);
        return true;
      }
      while (!st->lines.empty()) {
        std::string line = std::move(st->lines.front());
        st->lines.pop_front();
        lk.unlock();
        if (!sink.write(line.data(), line.size())) {  // browser went away → stop the agents
          if (!st->turn_id.empty()) h.cancel(st->turn_id);
          return false;
        }
        lk.lock();
      }
      if (st->done) sink.done();
      return true;
    });
  });

  svr.Post("/api/feedback", [&](const httplib::Request& req, httplib::Response& res) {
    auto j = json::parse(req.body, nullptr, false);
    if (!j.is_object()) return send_json(res, {{"error", "bad json"}}, 400);
    const int rating = j.value("rating", 0);
    if (rating != 1 && rating != -1) return send_json(res, {{"error", "rating must be 1 or -1"}}, 400);
    send_json(res, h.feedback(j.value("turn_id", ""), rating, j.value("comment", "")));
  });

  svr.Post("/api/cancel", [&](const httplib::Request& req, httplib::Response& res) {
    auto j = json::parse(req.body, nullptr, false);
    send_json(res, {{"ok", j.is_object() && h.cancel(j.value("turn_id", ""))}});
  });

  // Live feed of Walrus writes (Server-Sent Events).
  svr.Get("/api/writes", [&](const httplib::Request& req, httplib::Response& res) {
    const std::string uid = uid_of(req, res);
    auto cursor = std::make_shared<uint64_t>(0);
    {
      std::lock_guard lk(hub->mu);
      *cursor = hub->seq;
    }
    res.set_header("Cache-Control", "no-cache");
    res.set_chunked_content_provider("text/event-stream", [hub, cursor, uid](size_t, httplib::DataSink& sink) {
      std::vector<memwal::WriteRecord> out;
      {
        std::unique_lock lk(hub->mu);
        hub->cv.wait_for(lk, std::chrono::seconds(15), [&] { return hub->seq > *cursor; });
        for (auto& [s, r] : hub->events)
          if (s > *cursor && visible_to(r.ns, uid)) out.push_back(r);
        *cursor = hub->seq;
      }
      std::string payload = out.empty() ? ": keepalive\n\n" : "";
      for (auto& r : out) payload += "data: " + r.to_json().dump() + "\n\n";
      return sink.write(payload.data(), payload.size());
    });
  });

  std::printf("saga: listening on http://%s:%d%s\n", opt.host.c_str(), opt.port,
              opt.access_code.empty() ? "" : " (access code required)");
  std::fflush(stdout);
  if (!svr.listen(opt.host, opt.port)) {
    std::fprintf(stderr, "saga: cannot listen on %s:%d\n", opt.host.c_str(), opt.port);
    return 1;
  }
  return 0;
}

}  // namespace saga::web
